trigger:
- master

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Node6:
        node.version: 6.x
      Node8:
        node.version: 8.x
      Node10:
        node.version: 10.x
      Node11:
        node.version: 11.x
  steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: $(node.version)
  - script: npm install
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      verbose: false
      customCommand: run build
  - task: Npm@1
    displayName: 'npm run test'
    inputs:
      command: custom
      verbose: false
      customCommand: run test
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Test results for JavaScript'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '**/*-coverage.xml'
      reportDirectory: 'coverage'
      failIfCoverageEmpty: true
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm pack'
    inputs:
      command: custom
      verbose: false
      customCommand: pack
  - task: CopyFiles@2
    displayName: 'Copy Files to: drop'
    inputs:
      Contents: '*.tgz'
      TargetFolder: drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/drop
