trigger:
- master

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Node8:
        node.version: 8.x
      Node10:
        node.version: 10.x
      Node11:
        node.version: 11.x
  steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: $(node.version)
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: install
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      verbose: false
      customCommand: run build
  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: custom
      verbose: false
      customCommand: test
  - task: Npm@1
    displayName: 'npm run coverage'
    inputs:
      command: custom
      verbose: false
      customCommand: run coverage
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "$(System.DefaultWorkingDirectory)/test-results.xml"
      testRunTitle: "Test results for JavaScript"
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage/"
      failIfCoverageEmpty: true
- job: Pack
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm pack'
    inputs:
      command: custom
      verbose: false
      customCommand: pack
  - task: Npm@1
    displayName: 'npm run check:everything -- --azure-devops'
    inputs:
      command: custom
      verbose: false
      customCommand: run check:everything -- --azure-devops
  - task: CopyFiles@2
    displayName: 'Copy Files to: drop'
    inputs:
      Contents: '*.tgz'
      TargetFolder: drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/drop
